# Generated by Django 2.2 on 2020-03-23 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=50, verbose_name='Направление')),
                ('time', models.DateTimeField(verbose_name='Время выезда')),
                ('seats', models.IntegerField(verbose_name='Количество мест')),
                ('luggage', models.CharField(max_length=100, verbose_name='Багаж')),
                ('place_from', models.CharField(max_length=100, verbose_name='Пункт отправки')),
                ('place_to', models.CharField(max_length=100, verbose_name='Пункт прибытия')),
                ('car_number', models.CharField(max_length=15, verbose_name='Номер авто')),
                ('car', models.CharField(max_length=15, verbose_name='Номер авто')),
                ('price', models.IntegerField(verbose_name='Количество мест')),
                ('user', models.ManyToManyField(related_name='ad', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None, verbose_name='Мобильный телефон')),
                ('notification', models.BooleanField(verbose_name='Уведомления')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users_photo', verbose_name='Фото')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='webapp.City', verbose_name='Город')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_country', to='webapp.Country', verbose_name='Страна')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ads_photo', verbose_name='Фото')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='webapp.Ad', verbose_name='Обьявление')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('free', 'Свободен'), ('busy', 'Занят')], max_length=20, verbose_name='Статус')),
                ('car', models.CharField(max_length=50, verbose_name='Авто')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='webapp.Profile', verbose_name='Водитель')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='webapp.Country', verbose_name='Страна'),
        ),
    ]
