# Generated by Django 2.2 on 2020-03-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='ad',
            name='car',
            field=models.CharField(max_length=15, verbose_name='Марка авто'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
