# Generated by Django 2.2 on 2020-03-26 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_auto_20200323_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('client', 'Клиент'), ('driver', 'Водитель')], max_length=50, verbose_name='Тип')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Описание')),
                ('place_from', models.CharField(choices=[('Bishkek', 'Бишкек'), ('Chui', 'Чуй'), ('Talas', 'Талас'), ('Naryn', 'Нарын'), ('Issykkul', 'Иссыкуль'), ('Osh', 'Ош'), ('Jalal-Abad', 'Жалал-Абад'), ('Batken', 'Баткен')], max_length=100, verbose_name='Откуда')),
                ('place_to', models.CharField(choices=[('Bishkek', 'Бишкек'), ('Chui', 'Чуй'), ('Talas', 'Талас'), ('Naryn', 'Нарын'), ('Issykkul', 'Иссыкуль'), ('Osh', 'Ош'), ('Jalal-Abad', 'Жалал-Абад'), ('Batken', 'Баткен')], max_length=100, verbose_name='Куда')),
                ('departure_time', models.DateTimeField(verbose_name='Когда')),
                ('seats', models.IntegerField(verbose_name='Количество мест')),
                ('luggage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Багаж')),
                ('car_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Модель авто')),
                ('car_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер авто')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ads_photo', verbose_name='Фото')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершенный')], max_length=50, verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('clients', models.ManyToManyField(blank=True, null=True, related_name='experts', to=settings.AUTH_USER_MODEL, verbose_name='Область аккредитации')),
            ],
        ),
        migrations.RemoveField(
            model_name='photo',
            name='ad',
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
